providers:
  messagebird:
    access_key: 'live_qKwVZ02ULV70GqabBYxLU8d5r'
  nexmo:
    api_key: '18e0a6e9'
    api_secret: 'ea44c2d9'
  twilio:
    account_sid: 'aCb3bbaacc554b'
    auth_token: '4736473aaabbcc66'

receivers:
  - name: 'team-sms'
    provider: 'messagebird'
    to:
      - '+31612345678'
    from: 'Sachet'

